### ISSUE TITLE
pip install is failing

### ISSUE THREAD

**Issue by roman-mueller** [propyless/panopuppet#88]
I'm trying to install panopuppet via the instructions from the README, but the pip install step is failing:

```
(panopuppet)[root@centos6 repo]# cd /srv/repo/panopuppet
(panopuppet)[root@centos6 panopuppet]# pip install -r requirements.txt 
error: pathspec 'py3' did not match any file(s) known to git.
Downloading/unpacking git+https://github.com/rbarrois/python-ldap.git@py3 (from -r requirements.txt (line 4))
  Cloning https://github.com/rbarrois/python-ldap.git (to py3) to /tmp/pip-k4u0bg-build
  Could not find a tag or branch 'py3', assuming commit.
  Complete output from command /usr/bin/git checkout -q py3:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git checkout -q py3 failed with error code 1 in /tmp/pip-k4u0bg-build
Storing complete log in /root/.pip/pip.log
```

**Comment by propyless** [comment]
Hi there!

It looks like the python-ldap maintainers has decided to merge the py3 branch into master.
If you remove the @py3 from the python-ldap line in requirements it should just pull the latest stuff from the master branch.

Also, since #79 also will drop the python-ldap module in favour of pyldap you can remove the entire python-ldap line and add pyldap instead.

**Comment by propyless** [comment]
Fixed with #89 

Thanks for the report!
Feel free to reopen the issue if you stumble upon anymore errors. I know the readme is slightly outdated as of now. But i have a new version in the making with the core app pull request incoming.

If you used the IUS did you have to install python34 and now python33? There was also no mod_wsgi for python34 so I had to build that myself. You have anything more you want to add?

**Comment by roman-mueller** [comment]
Hi, thanks for the quick help!

I retried today without the `py3` tag but it still fails.
I only really tried using Python 3.3 so far (I did try 3.4 from IUS but I had trouble running `mkvirtualenv -p /usr/bin/python3 panopuppet` already and no time to debug yet).
It looks like django-auth-ldap pulls in the original python-ldap as a dependency:

```
Downloading/unpacking python-ldap>=2.0 (from django-auth-ldap==1.2.5->-r requirements.txt (line 3))
  Downloading python-ldap-2.4.22.tar.gz (121kB): 121kB downloaded
  Running setup.py egg_info for package python-ldap
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/srv/.virtualenvs/panopuppet/build/python-ldap/setup.py", line 53
        print name + ': ' + cfg.get('_ldap', name)
                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/srv/.virtualenvs/panopuppet/build/python-ldap/setup.py", line 53

    print name + ': ' + cfg.get('_ldap', name)

             ^

SyntaxError: invalid syntax
```

**Comment by propyless** [comment]
Hi, ok hmm interesting. Do you have an opputunity to hop into hipchat so i can help you in "realtime?"

https://www.hipchat.com/gGIEurYjr
Or irc, freenode #panopuppet channel.

**Comment by propyless** [comment]
problem resolved with latest master, updated django-auth-ldap to version 1.2.7 from 1.2.5. That in turn brought  in pyldap as a dependency for python 3.
